### ISSUE TITLE
Feature Request: Upload files to VirusTotal to be scanned

### ISSUE THREAD

**Issue by erev0s** [andpalmier/apkingo#1]
Currently the tool supports getting information from VT only if the apk already exists in VT. 
It would be nice to have the option to upload the file and wait for the results as well.

**Comment by andpalmier** [comment]
Hey, thanks for using apkingo, I'm working on this option.
I am not so sure about waiting for the results from VT, because the API are implemented to retrieve the progress of the file upload, but not the progress on the file analysis. Anyway, it would be possible to upload the file using the API key and show the URL of the file analysis. apkingo would then be able to interpret the results once the analysis is completed.

**Comment by erev0s** [comment]
@andpalmier would be great to see that option in the future. Great work so far!!
keep going!!

**Comment by andpalmier** [comment]
It should work now! Let me know.

**Comment by erev0s** [comment]
@andpalmier tried it out and it worked very nicely.
curious why you removed the options to pass the keys as parameters or the export as a json string (personally i believe the export is a valuable flag for static analysis - especially when you are analyzing in bulk)

thank you for your effort, great addition!
keep up the good work and hope to see many more features

**Comment by andpalmier** [comment]
Hi @erev0s thanks for trying out the app and for your feedback!
Regarding your question about the option to pass the keys as parameters or export as a JSON string, I removed that feature intentionally to keep the app minimal and user-friendly. However, I appreciate your suggestion and understand the value of the export option for static analysis. Unfortunately, I didn't like the way it was implemented before, so I decided to remove it.

That being said, I may introduce this feature again in the future if I find a more elegant solution to implement it. In the meantime, a possible workaround could be to have a sed script to parse the printed result into a structured JSON format.

Thanks again for your feedback and support! I'm always looking for ways to improve the app, so please don't hesitate to let me know if you have any other suggestions or feedback. :)
